export const PRODUCTS = [
  {
    _id: "0",
    photo: "https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg",
    name: "Aspirin",
    suppliers: "Square",
    stock: "12",
    price: "89.66",
    category: "Medicine",
  },
  {
    _id: "1",
    photo: "https://i.ibb.co/Hg0zZkQ/shop-4-7-1000x1000-min.jpg",
    name: "Paracetamol",
    suppliers: "Acme",
    stock: "19",
    price: "34.16",
    category: "Heart",
  },
  {
    _id: "2",
    photo: "https://i.ibb.co/02WmJdc/5-19-1000x1000-min.jpg",
    name: "Ibuprofen",
    suppliers: "Beximco",
    stock: "09",
    price: "53.76",
    category: "Head",
  },
  {
    _id: "3",
    photo: "https://i.ibb.co/GxTVSVk/shop-4-9-1000x1000-min.jpg",
    name: "Acetaminophen",
    suppliers: "ACI",
    stock: "14",
    price: "28.57",
    category: "Hand",
  },
  {
    _id: "4",
    photo: "https://i.ibb.co/X330FTj/shop-4-10-1000x1000-min.jpg",
    name: "Naproxen",
    suppliers: "Uniliver",
    stock: "10",
    price: "56.34",
    category: "Leg",
  },
  {
    _id: "5",
    photo: "https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg",
    name: "Amoxicillin",
    suppliers: "Square",
    stock: "25",
    price: "45.99",
    category: "Medicine",
  },
  {
    _id: "6",
    photo: "https://i.ibb.co/Hg0zZkQ/shop-4-7-1000x1000-min.jpg",
    name: "Lisinopril",
    suppliers: "Acme",
    stock: "17",
    price: "29.88",
    category: "Heart",
  },
  {
    _id: "7",
    photo: "https://i.ibb.co/02WmJdc/5-19-1000x1000-min.jpg",
    name: "Ciprofloxacin",
    suppliers: "Beximco",
    stock: "11",
    price: "38.45",
    category: "Head",
  },
  {
    _id: "8",
    photo: "https://i.ibb.co/GxTVSVk/shop-4-9-1000x1000-min.jpg",
    name: "Hydrochlorothiaz_ide",
    suppliers: "ACI",
    stock: "22",
    price: "24.76",
    category: "Hand",
  },
  {
    _id: "9",
    photo: "https://i.ibb.co/X330FTj/shop-4-10-1000x1000-min.jpg",
    name: "Prednisone",
    suppliers: "Uniliver",
    stock: "15",
    price: "48.99",
    category: "Leg",
  },
];
