import { Shop } from "@/types/shop";

export const STORES: Shop[] = [
  {
    _id: "123wwwwwwdqwe",
    shopName: "Huge Sale",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 5,
  },
  {
    _id: "123www34qwe",
    shopName: "Tremblay and Schiller ",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 4,
  },
  {
    _id: "123w576dqwe",
    shopName: "Huge Sale",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 3.7,
  },
  {
    _id: "123w779dgwe",
    shopName: "Huge Sale",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 5,
  },
  {
    _id: "984kfjf2",
    shopName: "Huge Sale",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 5,
  },
  {
    _id: "jkh435jkh",
    shopName: "Huge Sale",
    ownerName: "Petro",
    email: "test.mail.com",
    phone: "717-24-2429",
    streetAddress: "Albenia G83",
    city: "Seoul",
    postal: 37622,
    hasOwnDeliverySystem: false,
    rating: 2,
  },
];
